const assets = import.meta.glob(
  "/image/baekseok_gig_assets_20260930/webp/**/*.webp",
  { eager: true, query: "?url", import: "default" },
);
export const asset = (path) =>
  assets[`/image/baekseok_gig_assets_20260930/webp/${path}.webp`];
export const categories = [
  "전체보기",
  "디자인",
  "개발·IT",
  "영상·사진",
  "마케팅",
  "문서·번역",
  "기획·컨설팅",
  "학습·과외",
  "행사·운영",
  "기타",
];
export const services = {
  디자인: {
    "로고·브랜딩": [
      "로고 디자인",
      "브랜드 디자인·가이드",
      "명함·카드뉴스",
      "포스터·인쇄물",
      "패키지 디자인",
    ],
    "그래픽 디자인": [
      "상세페이지",
      "SNS·광고 디자인",
      "PPT·인포그래픽",
      "웹·앱 UI/UX",
      "일러스트·캐릭터",
    ],
    "공간·제품 디자인": [
      "인테리어·공간 디자인",
      "제품·굿즈 디자인",
      "3D 모델링·렌더링",
    ],
    "기타 디자인": ["캘리그라피·폰트", "타이포그래피", "전시·무대 디자인"],
  },
  "개발·IT": {
    "웹 개발": ["홈페이지 제작", "프론트엔드", "백엔드"],
    "앱·소프트웨어": ["모바일 앱", "자동화", "데이터 분석"],
  },
  "영상·사진": {
    영상: ["영상 편집", "모션그래픽", "숏폼 제작"],
    사진: ["행사 촬영", "제품 촬영", "사진 보정"],
  },
  "문서·번역": {
    문서: ["PPT 제작", "문서 교정", "데이터 정리"],
    번역: ["영문 번역", "영문 교정", "일문 번역"],
  },
  마케팅: { 콘텐츠: ["SNS 운영", "콘텐츠 제작", "홍보 기획"] },
  "기획·컨설팅": { 기획: ["서비스 기획", "사업계획서", "시장 조사"] },
  "학습·과외": { 교육: ["전공 과외", "외국어", "코딩 교육"] },
  "행사·운영": { 행사: ["행사 기획", "행사 운영", "공연"] },
  기타: { "기타 서비스": ["기타 업무"] },
};
export const experts = [
  {
    id: "e1",
    name: "김서연",
    specialty: "브랜드·그래픽 디자이너",
    category: "디자인",
    service: "브랜드 디자인·가이드",
    description:
      "브랜드의 가치를 시각적으로 표현합니다. 작은 아이디어도, 오래 기억되는 디자인으로.",
    tags: ["브랜딩", "포스터", "로고 디자인"],
    image: "expert-brand-card",
    homeImage: "expert-branding",
    avatar: 1,
    rating: 4.9,
    reviews: 32,
    completed: 28,
    response: 2,
    available: true,
  },
  {
    id: "e2",
    name: "이준호",
    specialty: "UI/UX · 웹 디자이너",
    category: "개발·IT",
    service: "프론트엔드",
    description:
      "사용자 중심의 직관적인 서비스를 만듭니다. 기획부터 반응형 웹 개발까지 함께해요.",
    tags: ["React", "Figma", "웹·앱 UI/UX"],
    image: "expert-uiux-card",
    homeImage: "expert-uiux",
    avatar: 2,
    rating: 4.8,
    reviews: 24,
    completed: 19,
    response: 3,
    available: true,
  },
  {
    id: "e3",
    name: "박민준",
    specialty: "영상 편집 · 모션그래픽",
    category: "영상·사진",
    service: "영상 편집",
    description:
      "영상에 이야기를 담는 편집자입니다. 홍보 영상부터 브이로그까지 감각적으로 완성해요.",
    tags: ["영상 편집", "Premiere Pro", "모션그래픽"],
    image: "expert-video-card",
    homeImage: "expert-video",
    avatar: 3,
    rating: 4.9,
    reviews: 28,
    completed: 35,
    response: 1,
    available: true,
  },
  {
    id: "e4",
    name: "이수민",
    specialty: "영문 번역 · 문서 교정",
    category: "문서·번역",
    service: "영문 번역",
    description:
      "정확하고 자연스러운 번역으로 더 넓은 세상을 연결합니다. 문장에 담긴 마음까지 옮겨요.",
    tags: ["영문 번역", "영문 교정", "비즈니스 문서"],
    image: "expert-translation-card",
    homeImage: "expert-translation",
    avatar: 4,
    rating: 4.8,
    reviews: 21,
    completed: 17,
    response: 3,
    available: false,
  },
  {
    id: "e5",
    name: "한유진",
    specialty: "행사 기획 · 콘텐츠 기획",
    category: "행사·운영",
    service: "행사 기획",
    description:
      "아이디어가 모여 특별한 행사가 됩니다. 모두가 기억할 순간을 함께 기획해요.",
    tags: ["행사 기획", "콘텐츠 기획", "행사 운영"],
    image: "expert-event",
    homeImage: "expert-event",
    avatar: 1,
    rating: 4.9,
    reviews: 31,
    completed: 40,
    response: 2,
    available: true,
  },
];
export const portfolios = [
  {
    id: "w1",
    title: "백석대학교 캠퍼스 브랜드 리디자인",
    description:
      "학교의 젊고 새로운 이미지를 담은 브랜드 로고 디자인 프로젝트입니다.",
    image: "campus-brand-design",
    category: "디자인",
    expertId: "e1",
    tags: ["브랜딩", "Illustrator"],
    likes: 124,
    views: "1.2k",
    verified: true,
  },
  {
    id: "w2",
    title: "우리의 오늘, 캠퍼스 홍보 영상",
    description: "캠퍼스의 일상을 담은 2분 분량의 홍보 영상입니다.",
    image: "campus-video-edit",
    category: "영상·사진",
    expertId: "e3",
    tags: ["영상 편집", "Premiere Pro"],
    likes: 98,
    views: "3.1k",
    verified: true,
  },
  {
    id: "w3",
    title: "더 편리한 캠퍼스 라이프, 학생 앱",
    description:
      "강의 시간표부터 학사 정보까지 한눈에 보는 모바일 앱 UI/UX입니다.",
    image: "student-app-uiux",
    category: "개발·IT",
    expertId: "e2",
    tags: ["Figma", "웹·앱 UI/UX"],
    likes: 215,
    views: "2.8k",
    verified: true,
  },
  {
    id: "w4",
    title: "다시 빛나는 우리, 백석 축제 포스터",
    description: "청춘의 에너지를 담은 축제 포스터 디자인 프로젝트입니다.",
    image: "baekseok-festa-poster",
    category: "디자인",
    expertId: "e1",
    tags: ["포스터", "Photoshop"],
    likes: 181,
    views: "2.1k",
    verified: true,
  },
  {
    id: "w5",
    title: "브랜드의 이야기를 담은 비주얼",
    description: "작은 브랜드의 시작을 위한 브랜드 아이덴티티 디자인.",
    image: "expert-branding",
    category: "디자인",
    expertId: "e1",
    tags: ["브랜딩", "Illustrator"],
    likes: 86,
    views: "960",
    verified: false,
  },
  {
    id: "w6",
    title: "특별한 순간을 기록하는 영상",
    description: "평범한 순간 속 특별한 이야기를 담았습니다.",
    image: "expert-video",
    category: "영상·사진",
    expertId: "e3",
    tags: ["영상 편집", "촬영"],
    likes: 72,
    views: "1.4k",
    verified: false,
  },
  {
    id: "w7",
    title: "언어를 넘어 마음을 연결하는 번역",
    description: "자연스럽게 읽히는 영문 소개 자료입니다.",
    image: "expert-translation",
    category: "문서·번역",
    expertId: "e4",
    tags: ["영문 번역", "영문 교정"],
    likes: 43,
    views: "720",
    verified: true,
  },
  {
    id: "w8",
    title: "함께 만들어 더 빛나는 축제",
    description: "기획부터 현장 운영까지 함께한 캠퍼스 행사.",
    image: "expert-event",
    category: "행사·운영",
    expertId: "e5",
    tags: ["행사 기획", "행사 운영"],
    likes: 112,
    views: "1.8k",
    verified: true,
  },
];
export const initialProjects = [
  {
    id: "p1",
    title: "학교 행사 포스터 디자인",
    category: "디자인",
    service: "포스터·인쇄물",
    summary:
      "학교 축제를 위한 포스터 디자인을 요청합니다. 젊고 트렌디한 분위기로 축제의 설렘을 담아주세요.",
    tags: ["포스터", "그래픽 디자인", "Illustrator"],
    budget: 100000,
    days: 7,
    deadline: "2026-10-05",
    owner: "이지현",
    image: "festa-poster-design",
    applicants: 8,
    mode: "온라인",
    status: "OPEN",
    createdAt: "2026-09-30T10:00:00",
    deliverables:
      "A2 사이즈 포스터 1종\nSNS 홍보 이미지 1종\n편집 가능한 원본 파일",
    content:
      "백석대학교 구성원이 함께하는 가을 행사 홍보물을 제작하려고 합니다.\n행사의 즐거운 분위기와 학생들의 에너지를 잘 표현해 주실 디자이너를 찾고 있어요. 행사 기획과 들어갈 문구는 준비되어 있습니다.",
    requirements:
      "밝고 트렌디한 분위기\n행사명, 날짜, 장소가 잘 보여야 해요\n인쇄와 SNS에 모두 활용할 예정이에요\n초안 이후 2회 수정을 희망합니다.",
  },
  {
    id: "p2",
    title: "동아리 소개 웹페이지 제작",
    category: "개발·IT",
    service: "홈페이지 제작",
    summary:
      "동아리 소개와 활동 기록을 담을 반응형 웹페이지를 만들고 싶어요. 간단한 게시판 기능도 필요합니다.",
    tags: ["React", "반응형", "프론트엔드"],
    budget: 300000,
    days: 14,
    deadline: "2026-10-12",
    owner: "박민준",
    image: "webpage-development",
    applicants: 5,
    mode: "온라인",
    status: "OPEN",
    createdAt: "2026-09-30T08:00:00",
    deliverables: "반응형 웹페이지\n소스 코드\n운영 안내 문서",
  },
  {
    id: "p3",
    title: "축제 스케치 영상 편집",
    category: "영상·사진",
    service: "영상 편집",
    summary:
      "백석대학교 축제 현장 스케치 영상을 편집해 주세요. 3~5분 분량으로 자막과 효과를 함께 부탁드려요.",
    tags: ["영상 편집", "Premiere Pro", "행사 편집"],
    budget: 200000,
    days: 10,
    deadline: "2026-10-03",
    owner: "김서연",
    image: "video-editing",
    applicants: 12,
    mode: "온라인",
    status: "OPEN",
    createdAt: "2026-09-29T14:00:00",
    deliverables: "3~5분 완성 영상\n세로형 숏폼 1종\n편집 프로젝트 파일",
  },
  {
    id: "p4",
    title: "카페 브랜드 로고 디자인",
    category: "디자인",
    service: "로고 디자인",
    summary:
      "교내에 오픈 예정인 카페의 브랜드 로고를 제작하고 싶습니다. 심플하면서도 따뜻한 느낌을 부탁드려요.",
    tags: ["로고 디자인", "브랜딩", "Illustrator"],
    budget: 150000,
    days: 7,
    deadline: "2026-10-06",
    owner: "정하늘",
    image: "brand-logo-design",
    applicants: 4,
    mode: "혼합",
    status: "OPEN",
    createdAt: "2026-09-29T10:00:00",
    deliverables: "로고 시안 2종\n최종 로고 원본\n간단한 사용 가이드",
  },
  {
    id: "p5",
    title: "영어 발표자료 교정 및 피드백",
    category: "문서·번역",
    service: "영문 교정",
    summary:
      "교환학생 지원을 위한 영문 자기소개서와 발표자료를 검토해 주실 분을 찾습니다.",
    tags: ["영문 교정", "영문 번역", "PPT"],
    budget: 50000,
    days: 5,
    deadline: "2026-10-08",
    owner: "국제교류팀",
    applicants: 3,
    mode: "온라인",
    status: "OPEN",
    createdAt: "2026-09-28T12:00:00",
    deliverables: "교정 문서\n문장별 피드백",
  },
  {
    id: "p6",
    title: "설문조사 데이터 정리 및 시각화",
    category: "기타",
    service: "기타 업무",
    summary:
      "설문조사 결과 데이터를 보기 좋게 정리하고, 간단한 분석과 시각화를 부탁드립니다.",
    tags: ["Excel", "데이터 정리", "데이터 분석"],
    budget: 80000,
    days: 5,
    deadline: "2026-10-09",
    owner: "사회복지학과",
    applicants: 2,
    mode: "온라인",
    status: "OPEN",
    createdAt: "2026-09-28T09:00:00",
    deliverables: "정리된 엑셀 파일\n분석 결과 차트",
  },
];
export const reviews = [
  {
    name: "이수민",
    department: "경영학과",
    work: "캠퍼스 브랜드 리디자인",
    text: "원하는 방향을 정확하게 이해해 주셨어요. 피드백도 빠르고 결과물도 정말 마음에 듭니다.",
  },
  {
    name: "정다은",
    department: "유아교육과",
    work: "영문 소개자료 번역",
    text: "단순한 번역을 넘어 더 자연스러운 표현까지 제안해 주셔서 큰 도움이 됐어요.",
  },
  {
    name: "김현우",
    department: "컴퓨터공학부",
    work: "학생 앱 UI/UX 디자인",
    text: "같은 학교라 소통이 편했어요. 작은 아이디어가 실제 결과물이 되는 경험이 좋았습니다.",
  },
  {
    name: "박지영",
    department: "간호학과",
    work: "축제 스케치 영상",
    text: "우리 학교의 분위기를 정말 잘 담아주셨어요. 다음 행사에서도 함께하고 싶어요!",
  },
];
